"use client";

/**
 * Floating message window opened from a Nudge button — mirrors LinkedIn's
 * docked chat widget. Messages live in local state only; nothing is persisted.
 * Suggested-message blocks are placeholders for a future Gemini integration.
 */
import { useEffect, useRef, useState } from "react";
import { Avatar, ConnectionBadge } from "@/components/linkedin";
import type { AttendeeRow } from "@/lib/eventTypes";

type NudgeChatProps = {
  attendee: AttendeeRow;
  onClose: () => void;
};

type ChatMessage = {
  id: number;
  text: string;
};

// Placeholder prompts shown as quick-fill blocks above the composer.
// These will be generated by the Gemini API later.
const SUGGESTED_MESSAGES = [
  "Great meeting you at the event! Would love to connect.",
  "Hi! I really enjoyed your insights — could I ask you a few questions?",
  "Thanks for coming out! Let's stay in touch.",
];

export function NudgeChat({ attendee, onClose }: NudgeChatProps) {
  const [draft, setDraft] = useState("");
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const nextId = useRef(1);
  const listRef = useRef<HTMLDivElement>(null);

  // Keep the latest message in view as the thread grows.
  useEffect(() => {
    listRef.current?.scrollTo({ top: listRef.current.scrollHeight });
  }, [messages]);

  function sendMessage() {
    const text = draft.trim();
    if (!text) return;
    setMessages((current) => [...current, { id: nextId.current++, text }]);
    setDraft("");
  }

  function handleKeyDown(event: React.KeyboardEvent<HTMLTextAreaElement>) {
    // Enter sends; Shift+Enter inserts a newline.
    if (event.key === "Enter" && !event.shiftKey) {
      event.preventDefault();
      sendMessage();
    }
  }

  return (
    <div
      className="nudge-chat"
      role="dialog"
      aria-label={`Message ${attendee.name}`}
    >
      <header className="nudge-chat__header">
        <div className="nudge-chat__person">
          <Avatar
            alt={attendee.name}
            src={attendee.profile_picture_url}
            size="sm"
          />
          <div className="nudge-chat__person-text">
            <p className="nudge-chat__name">
              {attendee.name}
              <ConnectionBadge degree={attendee.degree} />
            </p>
            <p className="nudge-chat__headline">{attendee.headline}</p>
          </div>
        </div>
        <button
          type="button"
          className="nudge-chat__close"
          aria-label="Close conversation"
          onClick={onClose}
        >
          ×
        </button>
      </header>

      <div className="nudge-chat__body" ref={listRef}>
        {messages.length === 0 ? (
          <p className="nudge-chat__empty">
            This is the start of your conversation with {attendee.name}.
          </p>
        ) : (
          messages.map((message) => (
            <div key={message.id} className="nudge-chat__message">
              {message.text}
            </div>
          ))
        )}
      </div>

      <div className="nudge-chat__suggestions">
        {SUGGESTED_MESSAGES.map((suggestion) => (
          <button
            key={suggestion}
            type="button"
            className="nudge-chat__suggestion"
            onClick={() => setDraft(suggestion)}
          >
            {suggestion}
          </button>
        ))}
      </div>

      <div className="nudge-chat__composer">
        <textarea
          className="nudge-chat__input"
          placeholder="Write a message…"
          value={draft}
          onChange={(event) => setDraft(event.target.value)}
          onKeyDown={handleKeyDown}
          rows={2}
        />
        <button
          type="button"
          className="nudge-chat__send"
          onClick={sendMessage}
          disabled={!draft.trim()}
        >
          Send
        </button>
      </div>
    </div>
  );
}
